-- MySQL Script generated by MySQL Workbench
-- Tue Dec 26 11:38:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema edubot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edubot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edubot` DEFAULT CHARACTER SET utf8mb4 ;
USE `edubot` ;

-- -----------------------------------------------------
-- Table `edubot`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`Users` (
  `UserID` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(64) NULL,
  `Surname` VARCHAR(64) CHARACTER SET 'big5' NULL,
  `GroupNumber` VARCHAR(64) NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edubot`.`UserFlags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`UserFlags` (
  `UserID` INT UNSIGNED NOT NULL,
  `StartDialogId` INT UNSIGNED NULL,
  `CurrentCourse` VARCHAR(45) NULL,
  `ActivePollMessageId` INT UNSIGNED NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `ID`
    FOREIGN KEY (`UserID`)
    REFERENCES `edubot`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edubot`.`UsersState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`UsersState` (
  `UserID` INT UNSIGNED NOT NULL,
  `DialogState` INT UNSIGNED NULL,
  `UserType` INT UNSIGNED NULL,
  `LogedIn` TINYINT(1) NULL,
  PRIMARY KEY (`UserID`),
  CONSTRAINT `ID2`
    FOREIGN KEY (`UserID`)
    REFERENCES `edubot`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edubot`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`Groups` (
  `GroupNumber` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`GroupNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edubot`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`Courses` (
  `CourseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CourseName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edubot`.`GroupsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edubot`.`GroupsCourses` (
  `GroupNumber` VARCHAR(45) NULL,
  `CourseName` VARCHAR(45) NULL,
  INDEX `GroupNumber_idx` (`GroupNumber` ASC) VISIBLE,
  INDEX `CourseName_idx` (`CourseName` ASC) VISIBLE,
  CONSTRAINT `GroupNumber`
    FOREIGN KEY (`GroupNumber`)
    REFERENCES `edubot`.`Groups` (`GroupNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseName`
    FOREIGN KEY (`CourseName`)
    REFERENCES `edubot`.`Courses` (`CourseName`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
